#!/usr/bin/env python3
"""Generate ``requirements/`` from ``Pipfile.lock``.

``Pipfile.lock`` stays the single source of truth for what this app depends on.
This script is the door between it and a bundle build, and it exists because
``pipenv requirements`` -- what ``build.sh`` used to call -- produces a file that
**cannot be installed on Windows**.

Two things it fixes:

1. **Platform markers.** ``pipenv requirements`` emits only the markers recorded
   in the lock, and the lock records none of the ``sys_platform`` constraints
   PyPI declares. So ``uvloop`` came out as a plain
   ``uvloop==0.22.1; python_full_version >= '3.8.1'`` and pip on Windows would
   try to build it from source and fail -- uvloop publishes no Windows wheels.
   ``_RESTORE_MARKERS`` puts back the marker the *upstream* package declares,
   copied verbatim from uvicorn's own metadata rather than paraphrased.

2. **torch's index.** The frozen file was a bare ``torch==2.13.0``, i.e. whatever
   the default PyPI wheel is. That is right for Apple silicon (MPS is built into
   the PyPI wheel) and useless for a CUDA build, which has to come from
   download.pytorch.org. torch is therefore split into its own per-target file
   and everything else lives in ``base.txt``.

Run it with ``--check`` to assert the committed files still match the lock; that
is what stops a bundle being built from stale pins.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LOCK = ROOT / "Pipfile.lock"
OUT = ROOT / "requirements"

# Markers PyPI declares that `pipenv requirements` drops on the floor. Copied
# **verbatim** from the upstream package's own metadata -- a paraphrase is how a
# marker ends up subtly wrong, and the whole point here is fidelity. uvicorn
# 0.52.0 declares uvloop as:
#
#   uvloop>=0.15.1; (sys_platform != "win32" and (sys_platform != "cygwin"
#                    and platform_python_implementation != "PyPy"))
#                    and extra == "standard"
#
# The `extra ==` clause is dropped because we are pinning the resolved package,
# not the optional dependency that pulled it in. The rest is reproduced exactly:
# cygwin and PyPy matter as much as win32 does, and guessing at "!= win32" alone
# would be a second, quieter version of the same bug.
_RESTORE_MARKERS = {
    "uvloop": (
        'sys_platform != "win32" and (sys_platform != "cygwin" '
        'and platform_python_implementation != "PyPy")'
    ),
}

# Pinned separately from base.txt because only its *index* varies by target.
_TORCH = "torch"

# The CUDA wheel series. One constant, because bumping it is one decision and
# every target that uses CUDA has to move together. Verified against
# download.pytorch.org: torch 2.13.0 is published for cu126 and cu130 (**not**
# cu128 or cu129), with cp313 wheels for win_amd64 on both -- which is what makes
# a Python 3.13 runtime viable for the future windows target.
_CUDA = "cu130"

# None means "the default PyPI wheel". For macOS arm64 that wheel already carries
# MPS, so there is no separate Apple index to point at -- the GPU support is in
# the stock package and `pick_device()` finds it at run time.
_TORCH_INDEX = {
    "mac": None,
    "cuda": f"https://download.pytorch.org/whl/{_CUDA}",
    "cpu": "https://download.pytorch.org/whl/cpu",
}

_HEADER = (
    "# GENERATED by tools/freeze.py from Pipfile.lock -- do not edit by hand.\n"
    "# Regenerate with:  python3 tools/freeze.py\n"
)


def _locked() -> dict[str, dict]:
    """The lock's resolved default packages, name -> entry."""
    try:
        data = json.loads(LOCK.read_text(encoding="utf-8"))
    except OSError as e:
        sys.exit(f"cannot read {LOCK}: {e}")
    except ValueError as e:
        sys.exit(f"{LOCK} is not valid JSON: {e}")
    return data.get("default") or {}


def _requirement(name: str, entry: dict) -> str | None:
    """One ``name==version; markers`` line, or None if it cannot be pinned."""
    version = entry.get("version")
    if not version:
        # A VCS or path dependency has no `version`. None today; if one is ever
        # added, saying so beats emitting a line that pins nothing.
        print(f"[freeze] skipping {name}: no pinned version in the lock",
              file=sys.stderr)
        return None

    markers = [m for m in (entry.get("markers"), _RESTORE_MARKERS.get(name)) if m]
    # Parenthesise before joining: the restored marker is itself a compound
    # expression, and `a and b or c` does not mean `a and (b or c)`.
    joined = " and ".join(f"({m})" for m in markers) if len(markers) > 1 else \
        (markers[0] if markers else "")
    return f"{name}{version}" + (f"; {joined}" if joined else "")


def _base_text(packages: dict[str, dict]) -> str:
    lines = [
        _HEADER,
        "# Everything except torch, which is per-target (see torch-*.txt).\n",
        "\n",
    ]
    for name in sorted(packages):
        if name == _TORCH:
            continue
        req = _requirement(name, packages[name])
        if req:
            lines.append(req + "\n")
    return "".join(lines)


def _torch_text(packages: dict[str, dict], target: str) -> str:
    entry = packages.get(_TORCH)
    if not entry:
        sys.exit(f"[freeze] {_TORCH} is not in {LOCK}")
    version = entry.get("version") or ""
    index = _TORCH_INDEX[target]

    lines = [_HEADER]
    if index:
        lines.append(
            f"# Not PyPI: this index serves the {target} build of torch.\n"
            "# Install this file with --no-deps; torch's dependencies are already\n"
            "# pinned in base.txt, and letting a second index resolve them again is\n"
            "# how you end up with two different versions of the same package.\n"
        )
        lines.append(f"--index-url {index}\n")
    else:
        lines.append(
            "# The stock PyPI wheel. On macOS arm64 it already contains MPS, so\n"
            "# there is no Apple-specific index -- `pick_device()` finds the GPU at\n"
            "# run time. Install with --no-deps; see base.txt.\n"
        )
    lines.append("\n")
    # The marker the lock carries for torch is a python_version floor, which is
    # true of every target and so says nothing useful in a file that exists to
    # distinguish them. The version pin is the point here.
    lines.append(f"{_TORCH}{version}\n")
    return "".join(lines)


def _files() -> dict[Path, str]:
    packages = _locked()
    if not packages:
        sys.exit(f"[freeze] no default packages found in {LOCK}")
    out = {OUT / "base.txt": _base_text(packages)}
    for target in _TORCH_INDEX:
        out[OUT / f"torch-{target}.txt"] = _torch_text(packages, target)
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--check", action="store_true",
        help="exit non-zero if the committed files differ from the lock, "
             "writing nothing",
    )
    args = ap.parse_args()

    wanted = _files()

    if args.check:
        stale = [
            p for p, text in wanted.items()
            if not p.exists() or p.read_text(encoding="utf-8") != text
        ]
        if stale:
            for p in stale:
                print(f"[freeze] out of date: {p.relative_to(ROOT)}", file=sys.stderr)
            print("[freeze] run: python3 tools/freeze.py", file=sys.stderr)
            return 1
        print(f"[freeze] {len(wanted)} file(s) match Pipfile.lock")
        return 0

    OUT.mkdir(exist_ok=True)
    for p, text in wanted.items():
        p.write_text(text, encoding="utf-8")
        print(f"[freeze] wrote {p.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
